#!/usr/bin/bash

#astuce keep up in background: ../../recup_tiles & disown

#Syntaxe pour tileview, mais je prefere garder les numeros de col/row dans les tiles et renommer ensuite. m'evite de re-telecharger a chaque fois
#ign-COL_ROW.jpg 
#0_0 1_0 2_0 3_0 ...
#0_1 1_1 2_1 3_1 ...
#0_2 1_2 2_2 3_2 ...
#0_3 1_3 2_3 3_3 ...

#http://tools.geofabrik.de/map/#16/43.9235/3.7230&type=Geofabrik_Standard&grid=1

source /home/geo/geo_functions.sh

#A l'ancienne: tu donnes deux coordonnées NW et SE
#Nouveau format pour les 4 coords: LAT_NW LNG_NW LAT_SE LNG_SE (delimiteur = espace)
#NW_SE="43.95285 3.857403 43.834589 4.108715" 
#read lat0 lng0 latN lngN < <(echo $NW_SE)

#Nouveau: tu donnes une coordonnée centrale et une distance en km qui sera ajoutée dans les 4 directions
read lat0 lng0 latN lngN < <(coord_to_bbox 43.782312 4.089646 10)
#15km --> 90Mo --> adb push 3 min

echo "lat0="$lat0 "lng0="$lng0 "latN="$latN "lngN="$lngN


ZOOM=16

XYNW=(`/home/geo/latlng $lat0 $lng0 $ZOOM`)
#XYNW=(`/initrd/mnt/dev_save/packages/GEO/playground_gdal/python/latlng $lat0 $lng0 16`)
X0=${XYNW[0]}
Y0=${XYNW[1]}
XYSE=(`/home/geo/latlng $latN $lngN $ZOOM`)
#XYSE=(`/initrd/mnt/dev_save/packages/GEO/playground_gdal/python/latlng $latN $lngN 16`)
XN=${XYSE[0]}
YN=${XYSE[1]}

echo $X0 $Y0 $XN $YN

mkdir ign 2>/dev/null
mkdir otm 2>/dev/null

fetch_otm () {
	if [ ! -f otm/otm-$2_$1.png ] 
	then
		echo "curl fetch row $1 col $2 zoom $ZOOM nom du fichier otm-$2_$1.png"
		curl https://a.tile.opentopomap.org/$ZOOM/$2/$1.png -o otm/otm-$2_$1.png
	fi
}

fetch_ign () {
	COL=$2
	ROW=$1
	if [ ! -f ign/ign-$2_$1.jpg ] 
	then
		echo "curl fetch row $1 col $2 zoom $ZOOM nom du fichier ign-$2_$1.jpg"
		curl "https://wxs.ign.fr/<ta clé ici>/geoportail/wmts?service=WMTS&request=GetTile&version=1.0.0&tilematrixset=PM&tilematrix=$ZOOM&tilecol=$COL&tilerow=$ROW&layer=GEOGRAPHICALGRIDSYSTEMS.MAPS&format=image/jpeg&style=normal" -o ign/ign-$2_$1.jpg
		#sleep 2 #pas envie de me faire mal voir chez ign...
	fi
}


for ((y=$Y0;y<=$YN;y++)); do
	for ((x=$X0;x<=$XN;x++)); do
		fetch_ign $y $x
		#fetch_otm $y $x 
	done    
done
